// Package exporter provides report export functionality with pluggable exporters.
package exporter

import (
	"fmt"
	"strings"
	"time"

	"github.com/verustcode/verustcode/internal/model"
)

// MarkdownExporter exports reports to Markdown format
type MarkdownExporter struct{}

// NewMarkdownExporter creates a new Markdown exporter
func NewMarkdownExporter() *MarkdownExporter {
	return &MarkdownExporter{}
}

// Export exports a report to Markdown format
func (e *MarkdownExporter) Export(rpt *model.Report, sections []model.ReportSection) (string, error) {
	var content string

	if rpt.Content != "" {
		// Use the already merged content
		content = rpt.Content
	} else {
		// Merge sections into content
		content = MergeSections(rpt, sections)
	}

	return e.formatMarkdownWithMetadata(rpt, content), nil
}

// Name returns the human-readable name of this exporter
func (e *MarkdownExporter) Name() string {
	return "Markdown"
}

// FileExtension returns the file extension for Markdown files
func (e *MarkdownExporter) FileExtension() string {
	return ".md"
}

// formatMarkdownWithMetadata adds metadata header to the markdown content
func (e *MarkdownExporter) formatMarkdownWithMetadata(rpt *model.Report, content string) string {
	var sb strings.Builder

	// Add YAML front matter for metadata
	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("title: \"%s\"\n", escapeYAMLString(rpt.Title)))
	sb.WriteString(fmt.Sprintf("report_type: %s\n", rpt.ReportType))
	sb.WriteString(fmt.Sprintf("repository: %s\n", rpt.RepoURL))
	sb.WriteString(fmt.Sprintf("ref: %s\n", rpt.Ref))
	sb.WriteString(fmt.Sprintf("generated_at: %s\n", time.Now().Format(time.RFC3339)))
	if rpt.Duration > 0 {
		sb.WriteString(fmt.Sprintf("generation_time_ms: %d\n", rpt.Duration))
	}
	sb.WriteString("generator: VerustCode\n")
	sb.WriteString("---\n\n")

	// Add content
	sb.WriteString(content)

	// Add footer
	sb.WriteString("\n\n---\n\n")
	sb.WriteString("*Generated by [VerustCode](https://github.com/verustcode/verustcode)*\n")

	return sb.String()
}
