package output

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/verustcode/verustcode/internal/config"
)

func TestBuildMetadataString_NilConfig(t *testing.T) {
	result := BuildMetadataString(nil, "cursor", "gpt-4")
	assert.Empty(t, result)
}

func TestBuildMetadataString_WithCustomText(t *testing.T) {
	cfg := &config.OutputMetadataConfig{
		CustomText: "Generated by VerustCode",
	}

	result := BuildMetadataString(cfg, "cursor", "gpt-4")
	assert.Contains(t, result, "Generated by VerustCode")
	assert.Contains(t, result, "Agent: cursor")
	assert.Contains(t, result, "Model: gpt-4")
}

func TestBuildMetadataString_ShowAgentDisabled(t *testing.T) {
	showAgent := false
	cfg := &config.OutputMetadataConfig{
		ShowAgent: &showAgent,
		ShowModel: boolPtr(true),
	}

	result := BuildMetadataString(cfg, "cursor", "gpt-4")
	assert.NotContains(t, result, "Agent:")
	assert.Contains(t, result, "Model: gpt-4")
}

func TestBuildMetadataString_ShowModelDisabled(t *testing.T) {
	showModel := false
	cfg := &config.OutputMetadataConfig{
		ShowAgent: boolPtr(true),
		ShowModel: &showModel,
	}

	result := BuildMetadataString(cfg, "cursor", "gpt-4")
	assert.Contains(t, result, "Agent: cursor")
	assert.NotContains(t, result, "Model:")
}

func TestBuildMetadataString_BothDisabled(t *testing.T) {
	showAgent := false
	showModel := false
	cfg := &config.OutputMetadataConfig{
		ShowAgent:  &showAgent,
		ShowModel:  &showModel,
		CustomText: "Custom text",
	}

	result := BuildMetadataString(cfg, "cursor", "gpt-4")
	assert.Contains(t, result, "Custom text")
	assert.NotContains(t, result, "Agent:")
	assert.NotContains(t, result, "Model:")
}

func TestBuildMetadataString_EmptyAgentName(t *testing.T) {
	cfg := &config.OutputMetadataConfig{
		ShowAgent: boolPtr(true),
		ShowModel: boolPtr(true),
	}

	result := BuildMetadataString(cfg, "", "gpt-4")
	assert.NotContains(t, result, "Agent:")
	assert.Contains(t, result, "Model: gpt-4")
}

func TestBuildMetadataString_EmptyModelName(t *testing.T) {
	cfg := &config.OutputMetadataConfig{
		ShowAgent: boolPtr(true),
		ShowModel: boolPtr(true),
	}

	result := BuildMetadataString(cfg, "cursor", "")
	assert.Contains(t, result, "Agent: cursor")
	assert.NotContains(t, result, "Model:")
}

func TestBuildMetadataString_DefaultShow(t *testing.T) {
	// When ShowAgent/ShowModel are nil, they default to true
	cfg := &config.OutputMetadataConfig{}

	result := BuildMetadataString(cfg, "cursor", "gpt-4")
	assert.Contains(t, result, "Agent: cursor")
	assert.Contains(t, result, "Model: gpt-4")
}

func TestBuildMetadataString_Format(t *testing.T) {
	cfg := &config.OutputMetadataConfig{
		CustomText: "Custom",
		ShowAgent:  boolPtr(true),
		ShowModel:  boolPtr(true),
	}

	result := BuildMetadataString(cfg, "cursor", "gpt-4")
	assert.True(t, strings.HasPrefix(result, "*"))
	assert.True(t, strings.HasSuffix(result, "*"))
	assert.Contains(t, result, " || ")
}
