package config

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDefault(t *testing.T) {
	cfg := Default()

	// 验证 Server 默认值
	if cfg.Server.Host != "0.0.0.0" {
		t.Errorf("Server.Host = %v, want 0.0.0.0", cfg.Server.Host)
	}
	if cfg.Server.Port != 8080 {
		t.Errorf("Server.Port = %v, want 8080", cfg.Server.Port)
	}
	if cfg.Server.Debug {
		t.Error("Server.Debug should be false by default")
	}

	// 验证 Review.Workspace 默认值
	if cfg.Review.Workspace != "./workspace" {
		t.Errorf("Review.Workspace = %v, want ./workspace", cfg.Review.Workspace)
	}

	// 验证 Agents 默认值
	if cfg.Agents == nil {
		t.Error("Agents should not be nil")
	}
	if len(cfg.Agents) == 0 {
		t.Error("Agents should have at least one agent configured")
	}
	if cursorAgent, ok := cfg.Agents["cursor"]; !ok {
		t.Error("Agents should have cursor agent configured")
	} else if cursorAgent.CLIPath != "/usr/local/bin/cursor" {
		t.Errorf("Agents[\"cursor\"].CLIPath = %v, want /usr/local/bin/cursor", cursorAgent.CLIPath)
	}

	// 验证 Review 默认值
	if cfg.Review.MaxConcurrent != 3 {
		t.Errorf("Review.MaxConcurrent = %v, want 3", cfg.Review.MaxConcurrent)
	}

	// 验证 OutputMetadata 默认值
	if cfg.Review.OutputMetadata.ShowAgent == nil || !*cfg.Review.OutputMetadata.ShowAgent {
		t.Error("Review.OutputMetadata.ShowAgent should be true by default")
	}
	if cfg.Review.OutputMetadata.ShowModel == nil || !*cfg.Review.OutputMetadata.ShowModel {
		t.Error("Review.OutputMetadata.ShowModel should be true by default")
	}
	if cfg.Review.OutputMetadata.CustomText != "Generated by [VerustCode](https://github.com/verustcode/verustcode)" {
		t.Errorf("Review.OutputMetadata.CustomText = %v, want default text", cfg.Review.OutputMetadata.CustomText)
	}

	// 验证 Logging 默认值
	if cfg.Logging.Level != "info" {
		t.Errorf("Logging.Level = %v, want info", cfg.Logging.Level)
	}
}

func TestServerConfig_Address(t *testing.T) {
	tests := []struct {
		name string
		host string
		port int
		want string
	}{
		{
			name: "default address",
			host: "0.0.0.0",
			port: 8080,
			want: "0.0.0.0:8080",
		},
		{
			name: "localhost",
			host: "localhost",
			port: 3000,
			want: "localhost:3000",
		},
		{
			name: "custom host and port",
			host: "192.168.1.100",
			port: 9090,
			want: "192.168.1.100:9090",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := &ServerConfig{
				Host: tt.host,
				Port: tt.port,
			}
			got := cfg.Address()
			if got != tt.want {
				t.Errorf("Address() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestGitConfig_GetProvider(t *testing.T) {
	cfg := &GitConfig{
		Providers: []ProviderConfig{
			{Type: "github", Token: "github-token"},
			{Type: "gitlab", Token: "gitlab-token", URL: "https://gitlab.example.com"},
		},
	}

	tests := []struct {
		name         string
		providerType string
		wantFound    bool
		wantToken    string
	}{
		{
			name:         "find github",
			providerType: "github",
			wantFound:    true,
			wantToken:    "github-token",
		},
		{
			name:         "find gitlab",
			providerType: "gitlab",
			wantFound:    true,
			wantToken:    "gitlab-token",
		},
		{
			name:         "provider not found",
			providerType: "bitbucket",
			wantFound:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			provider := cfg.GetProvider(tt.providerType)
			if tt.wantFound {
				if provider == nil {
					t.Errorf("GetProvider(%s) returned nil, want provider", tt.providerType)
					return
				}
				if provider.Token != tt.wantToken {
					t.Errorf("GetProvider(%s).Token = %v, want %v", tt.providerType, provider.Token, tt.wantToken)
				}
			} else {
				if provider != nil {
					t.Errorf("GetProvider(%s) = %v, want nil", tt.providerType, provider)
				}
			}
		})
	}
}

func TestConfig_GetAgent(t *testing.T) {
	cfg := &Config{
		Agents: map[string]AgentDetail{
			"cursor": {CLIPath: "/usr/local/bin/cursor", Timeout: 600},
			"gemini": {CLIPath: "/usr/local/bin/gemini", APIKey: "api-key", Timeout: 300},
		},
	}

	tests := []struct {
		name      string
		agentName string
		wantFound bool
		wantPath  string
	}{
		{
			name:      "find cursor",
			agentName: "cursor",
			wantFound: true,
			wantPath:  "/usr/local/bin/cursor",
		},
		{
			name:      "find gemini",
			agentName: "gemini",
			wantFound: true,
			wantPath:  "/usr/local/bin/gemini",
		},
		{
			name:      "agent not found",
			agentName: "openai",
			wantFound: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			agent := cfg.GetAgent(tt.agentName)
			if tt.wantFound {
				if agent == nil {
					t.Errorf("GetAgent(%s) returned nil, want agent", tt.agentName)
					return
				}
				if agent.CLIPath != tt.wantPath {
					t.Errorf("GetAgent(%s).CLIPath = %v, want %v", tt.agentName, agent.CLIPath, tt.wantPath)
				}
			} else {
				if agent != nil {
					t.Errorf("GetAgent(%s) = %v, want nil", tt.agentName, agent)
				}
			}
		})
	}
}

func TestLoad(t *testing.T) {
	// 创建临时配置文件
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "config.yaml")

	configContent := `
server:
  host: "127.0.0.1"
  port: 9000
  debug: true

git:
  providers:
    - type: github
      token: test-token

agents:
  cursor:
    cli_path: /test/cursor
    timeout: 300

review:
  workspace: "./test-workspace"
  max_concurrent: 5

logging:
  level: debug
  format: text
`

	if err := os.WriteFile(configPath, []byte(configContent), 0644); err != nil {
		t.Fatalf("Failed to write test config file: %v", err)
	}

	cfg, err := Load(configPath)
	if err != nil {
		t.Fatalf("Load() unexpected error: %v", err)
	}

	// 验证加载的值
	if cfg.Server.Host != "127.0.0.1" {
		t.Errorf("Server.Host = %v, want 127.0.0.1", cfg.Server.Host)
	}
	if cfg.Server.Port != 9000 {
		t.Errorf("Server.Port = %v, want 9000", cfg.Server.Port)
	}
	if !cfg.Server.Debug {
		t.Error("Server.Debug should be true")
	}
	if cfg.Review.Workspace != "./test-workspace" {
		t.Errorf("Review.Workspace = %v, want ./test-workspace", cfg.Review.Workspace)
	}
	if cfg.Review.MaxConcurrent != 5 {
		t.Errorf("Review.MaxConcurrent = %v, want 5", cfg.Review.MaxConcurrent)
	}
	if cfg.Logging.Level != "debug" {
		t.Errorf("Logging.Level = %v, want debug", cfg.Logging.Level)
	}
}

func TestLoad_EnvVarExpansion(t *testing.T) {
	// 设置环境变量
	os.Setenv("TEST_GITHUB_TOKEN", "env-github-token")
	defer os.Unsetenv("TEST_GITHUB_TOKEN")

	// 创建临时配置文件
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "config.yaml")

	configContent := `
git:
  providers:
    - type: github
      token: ${TEST_GITHUB_TOKEN}
`

	if err := os.WriteFile(configPath, []byte(configContent), 0644); err != nil {
		t.Fatalf("Failed to write test config file: %v", err)
	}

	cfg, err := Load(configPath)
	if err != nil {
		t.Fatalf("Load() unexpected error: %v", err)
	}

	provider := cfg.Git.GetProvider("github")
	if provider == nil {
		t.Fatal("GitHub provider not found")
	}
	if provider.Token != "env-github-token" {
		t.Errorf("Provider.Token = %v, want env-github-token", provider.Token)
	}
}

func TestLoad_EnvVarWithDefault(t *testing.T) {
	// 确保环境变量不存在
	os.Unsetenv("NONEXISTENT_VAR")

	// 创建临时配置文件
	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "config.yaml")

	configContent := `
review:
  workspace: ${NONEXISTENT_VAR:-./default-workspace}
`

	if err := os.WriteFile(configPath, []byte(configContent), 0644); err != nil {
		t.Fatalf("Failed to write test config file: %v", err)
	}

	cfg, err := Load(configPath)
	if err != nil {
		t.Fatalf("Load() unexpected error: %v", err)
	}

	if cfg.Review.Workspace != "./default-workspace" {
		t.Errorf("Review.Workspace = %v, want ./default-workspace", cfg.Review.Workspace)
	}
}

func TestLoad_FileNotFound(t *testing.T) {
	_, err := Load("/nonexistent/path/config.yaml")
	if err == nil {
		t.Error("Load() expected error for nonexistent file, got nil")
	}
}
